/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Visao;
import Controle.AtualizadoHora;
import Controle.ConectaBanco;
import Controle.ControleVenda;
import Controle.ControleVendaControle;
import Controle.Mensagem;
import Modelo.ModeloTabela;
import Modelo.ModeloVenda;
import Modelo.ModeloVendaControle;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Eduardo
 */
public class Vendas extends javax.swing.JFrame {
    
    
 DecimalFormat formato;// Variavel global para DecimalFormat
    
 ConectaBanco conn = new ConectaBanco();
  
 ControleVenda control = new ControleVenda();
 ControleVendaControle controle = new ControleVendaControle();
 
 ModeloVenda md = new ModeloVenda();
 ModeloVendaControle mdc = new ModeloVendaControle();
 Mensagem volte = new Mensagem("Obrigado e volte sempre ."); // Uma mensagem para ser impressa quando o pedido for finalizado.

 int i=1,j=1,cont=1;
 float total=0 ; // variavel global para icrementar o preço
 int flag=1;
 float z,w,T,x , y, t  ;
 int rep=0; // contador para deletar os produtos na tabela
 
    /**
     * Creates new form Vendas
     */
    public Vendas() {
        initComponents();
        
       
        
        formato = new DecimalFormat("#0.00"); // Cria um campo para pegar dois numeros apos o ponto.
        
        
        AtualizadoHora.start(Hora); // Para colocar a Hora no sistema
        
        
        //Pega data do sistema
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date hoje = new Date();
        Data.setText(df.format(hoje));
        
        
        
        //JOptionPane.showMessageDialog(rootPane, "Utilize o boão pesquizar para adicionar produtos na tabela abaixo!");        
        //JOptionPane.showMessageDialog(rootPane, "Clique na tabela e esolha o produto e clique em pesquisar para atualizar!");        
        
         URL url = this.getClass().getResource("/Imagem/açai.png");  //coloca a imagem no lugar da tigela java
          Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);  
            this.setIconImage(imagemTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldProdConsu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jToggleButtonPesqProd = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDinheiro = new javax.swing.JTextField();
        jButtonFinalizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        VoltSempre = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        Hora = new javax.swing.JLabel();
        Data = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        Somar = new javax.swing.JButton();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel14 = new javax.swing.JLabel();
        jLabelDinheiro = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        VALOR = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelValorTroco = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldPreco1 = new javax.swing.JTextField();
        jTextFieldPreco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCodigoVenda = new javax.swing.JTextField();
        DeletarTabelaControle = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calcular vendas");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Escolha os produtos:");

        jTextFieldProdConsu.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextFieldProdConsu.setForeground(new java.awt.Color(0, 102, 102));
        jTextFieldProdConsu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldProdConsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProdConsuActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TableMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TableMouseEntered(evt);
            }
        });
        Table.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TableFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                TableFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jToggleButtonPesqProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search.png"))); // NOI18N
        jToggleButtonPesqProd.setToolTipText("Pesquisar e Atualizar");
        jToggleButtonPesqProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPesqProdActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("Dinheiro :");

        jTextFieldDinheiro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldDinheiro.setForeground(new java.awt.Color(51, 102, 0));
        jTextFieldDinheiro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept.png"))); // NOI18N
        jButtonFinalizar.setToolTipText("Digite o valor do dinheiro e Clique aqui para finalizar");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText("Produtos Consumidos");

        jLabel9.setText("R$");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 51));
        jLabel11.setText("Codigo");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jDesktopPane1.setBackground(new java.awt.Color(102, 0, 102));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/açai.png"))); // NOI18N

        VoltSempre.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        VoltSempre.setForeground(new java.awt.Color(255, 255, 255));
        VoltSempre.setText("Seja bem vindo !");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352)
                .addComponent(VoltSempre, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VoltSempre)
                .addGap(28, 28, 28))
        );
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(VoltSempre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane2.setBackground(new java.awt.Color(153, 0, 153));

        Hora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Hora.setForeground(new java.awt.Color(255, 255, 255));
        Hora.setText("Hora");

        Data.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Data.setForeground(new java.awt.Color(255, 255, 255));
        Data.setText("Data");

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Hora)
                .addGap(59, 59, 59)
                .addComponent(Data)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hora)
                    .addComponent(Data)))
        );
        jDesktopPane2.setLayer(Hora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(Data, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mesa 1", "mesa 2", "mesa 3", "mesa 4", "mesa 5", "mesa 6", "mesa 7", "mesa 8", "mesa 9", "mesa 10", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        Somar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        Somar.setToolTipText("Somar");
        Somar.setEnabled(false);
        Somar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SomarActionPerformed(evt);
            }
        });

        jDesktopPane3.setBackground(new java.awt.Color(0, 51, 153));
        jDesktopPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 3));
        jDesktopPane3.setForeground(new java.awt.Color(51, 51, 51));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Dinheiro :");

        jLabelDinheiro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDinheiro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDinheiro.setText("Valor");

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("R$");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TOTAL:");

        VALOR.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        VALOR.setForeground(new java.awt.Color(255, 255, 255));
        VALOR.setText("Valor");

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("R$");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TROCO:");

        jLabelValorTroco.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabelValorTroco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValorTroco.setText("Valor");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("R$");

        jTextFieldPreco1.setBackground(new java.awt.Color(0, 51, 153));
        jTextFieldPreco1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPreco1.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPreco1.setBorder(null);

        jTextFieldPreco.setBackground(new java.awt.Color(0, 51, 153));
        jTextFieldPreco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPreco.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPreco.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Unitario:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("R$");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("R$");

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(VALOR, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelValorTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabelDinheiro)
                    .addComponent(jLabel15))
                .addGap(33, 33, 33)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(VALOR)
                    .addComponent(jLabel13))
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelValorTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(32, 32, 32))
        );
        jDesktopPane3.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabelDinheiro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(VALOR, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabelValorTroco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jTextFieldPreco1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jTextFieldPreco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldCodigoVenda.setEnabled(false);

        DeletarTabelaControle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeletarTabelaControle.setForeground(new java.awt.Color(51, 153, 0));
        DeletarTabelaControle.setText("Finalizar os pedidos da tabela");
        DeletarTabelaControle.setToolTipText("Limpar Tabela");
        DeletarTabelaControle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 3));
        DeletarTabelaControle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DeletarTabelaControle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarTabelaControleActionPerformed(evt);
            }
        });

        jProgressBar1.setForeground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                            .addComponent(DeletarTabelaControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldProdConsu, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButtonPesqProd)
                                .addGap(10, 10, 10)
                                .addComponent(Somar)))
                        .addGap(109, 109, 109)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFinalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(858, 858, 858)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Somar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldProdConsu, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                            .addComponent(jToggleButtonPesqProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeletarTabelaControle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jTextFieldDinheiro)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonPesqProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPesqProdActionPerformed
        // TODO add your handling code here:
       
      
     if(!jTextFieldProdConsu.getText().equals("")){
        conn.conexao();
         preencherTabelaProduto("select * from produto where nome_produto like'%"+jTextFieldProdConsu.getText()+"%' ");
           
         jTextFieldProdConsu.setText("");
         
         // aqui e necessario fazer apenas x
        
             float x; 
          
                x =Float.parseFloat(jTextFieldPreco.getText());
                  
                     jTextFieldPreco.setText(""); // Recebe o primeiro valor e limpa a tela
        
          jTextFieldPreco1.setText(String.valueOf(x)); // Recebe o valor total atualizado
          
         
         
          
        }else{
              JOptionPane.showMessageDialog(rootPane,"Informe um produto válido!");
               JOptionPane.showMessageDialog(rootPane, "E clique no produto para adiciona-lo!");
        }
         
        
           
    }//GEN-LAST:event_jToggleButtonPesqProdActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
      float soma;// variavel de referencia
      
         if(flag==1){
             String produto = ""+Table.getValueAt(Table.getSelectedRow(),0);// nome para a tabela
            // jTextFieldNomeProdutos.setText(produto);
              String preco1 = ""+Table.getValueAt(Table.getSelectedRow(),1);// preço para o jtxtFieldPreco
              
             preencherTabelaVendaNomeProdutos1();// mostra os produtos na tabela1
             
          md.setNomepd(produto);// salva no banco
          md.setPreco(Float.parseFloat(preco1));
          
                md.setnMesa((String)jComboBox1.getSelectedItem()); // lança a mesa no banco 
                 md.setData(Data.getText());// lança a data no banco
                 md.setHora(Hora.getText());// lança a hora no banco
                    control.Salvar(md); // Salva
                    
                    mdc.setNomepd(produto);// salva no banco
                    mdc.setPreco(Float.parseFloat(preco1));
                     mdc.setnMesa((String)jComboBox1.getSelectedItem()); // lança a mesa no banco 
                      mdc.setData(Data.getText());
                        mdc.setHora(Hora.getText());
                           controle.Salvar(mdc);
                      
                      
             
             String preco = ""+Table.getValueAt(Table.getSelectedRow(),1);// preço para o jtxtFieldPreco
            
             jTextFieldPreco.setText(preco);// mostra o preço em string
             //jTextFieldPreco.setText("");
             
             soma=Float.parseFloat(preco);// converte o preço para float
             
             total=total+soma; // incrementa o preço
             
             jTextFieldPreco1.setText(String.valueOf(total));
             
             
             VALOR.setText(formato.format(total));//Imprime dois numeros apos o ponto.
             
             
             //jTextFieldPreco.setText(preco);
             
          
              
            
        }
         
    }//GEN-LAST:event_TableMouseClicked

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
    
         
         
         // TODO add your handling code here:
         if(!jTextFieldDinheiro.getText().equals("")){
             //float z,w,T;
             T = Float.parseFloat(jTextFieldDinheiro.getText())-Float.parseFloat(jTextFieldPreco1.getText());
             z=Float.parseFloat(jTextFieldDinheiro.getText());
             w=Float.parseFloat(jTextFieldPreco1.getText());
             
             T=z-w;
             
             jLabelDinheiro.setText(formato.format(z)); // Valor do dinheiro com duas casa apos o ponto.
             //jLabelValorTroco.setText(String.valueOf(T));
             jLabelValorTroco.setText(formato.format(T)); //utiliza o DecimalFormat para imprimir dois numeros apos o ponto.
            
             jTextFieldPreco.setText("");
             jTextFieldPreco1.setText("");
             jTextFieldDinheiro.setText("");
             //JOptionPane.showMessageDialog(rootPane,"Pedido Finalizado!");
             
             
              VoltSempre.setText(volte.getMensagem()); // Imprime a mensagem Obrigado e volte sempre.
                 
         }else{
             JOptionPane.showMessageDialog(rootPane,"Digite o valor do dinheiro!");
         }
         
         conn.conexao();
         
         //conn.rs.first();
         // atualiza a tabela
         preencherTabelaVendaNomeProdutosContole("select * from vendacontrole where nomepd_venda like'%"+jButtonFinalizar.getText()+"%' ");
         
         
         
         //FrmTabelaVenda frm = new FrmTabelaVenda();
         //frm.setVisible(true);
     
     
    
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void TableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TableFocusGained
        // TODO add your handling code here:
       /* float x,y, t=0;   
                x =Float.parseFloat(jTextFieldPreco.getText());
        
                 y= Float.parseFloat(jTextFieldPreco1.getText());
                 t = x+y;
       
                     jTextFieldPreco.setText("");
        
                  jTextFieldPreco1.setText(String.valueOf(t));  */
        
    }//GEN-LAST:event_TableFocusGained

    private void TableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TableFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TableFocusLost

    private void jTextFieldProdConsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProdConsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProdConsuActionPerformed

    private void TableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseEntered
        // TODO add your handling code here:
         
    }//GEN-LAST:event_TableMouseEntered

    private void TableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TableMouseReleased

    private void SomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SomarActionPerformed
        // TODO add your handling code here:
        
    
        if(!jTextFieldPreco1.getText().equals("")){
           // float x , y, t ;
            
            x =Float.parseFloat(jTextFieldPreco.getText());
            y =Float.parseFloat(jTextFieldPreco1.getText());
            
            t= x + y;
            
            jTextFieldPreco.setText(""); // Recebe o primeiro valor e limpa a tela
            
            jTextFieldPreco1.setText(String.valueOf(t)); // Recebe o valor total atualizado
            total = t + 0; // calcula o total
            //VALOR.setText(String.valueOf(total));
             VALOR.setText(formato.format(t));//Imprime dois numeros apos o ponto.
       
        }else{
          JOptionPane.showMessageDialog(rootPane,"Incremente outro produto !");  
        }
        
        
    }//GEN-LAST:event_SomarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jComboBox1.setEnabled(!true);// depois que o item for selecionado a caixa desabilita
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void DeletarTabelaControleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarTabelaControleActionPerformed
        // TODO add your handling code here:
        
        
       
             
        while(rep < 15){ // deleta 15 linhas com apenas um clique
            mdc=controle.VendaPrimeiro();
            conn.execultasql("select * from vendacontrole where id_venda='"+mdc.getIdVenda()+"'");//Apenas selecionar e excluir
            controle.Excluir(mdc);// para excluir
            preencherTabelaVendaNomeProdutosContole("select * from vendacontrole"); // agora preenche a tabela no banco
            rep++;
        
        
        }
        JOptionPane.showMessageDialog(rootPane,"Pedido Finalizado! ");
         // Fecha e abre a tela ao mesmo tempo.
        dispose();// fecha a tela
        new Vendas().setVisible(true);// Abre a tela novamente
      
        
        
        
    }//GEN-LAST:event_DeletarTabelaControleActionPerformed
    
    
     public void preencherTabelaProduto(String sql){
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Nome","preço"};
        conn.conexao();
        conn.execultasql(sql);                
            try {               
               
                conn.rs.first();
                do {
                    
                    dados.add(new Object[]{conn.rs.getString("nome_produto"),conn.rs.getString("preco_produto")});
                    
                }while(conn.rs.next());
            } catch (SQLException ex) {
               // JOptionPane.showMessageDialog(rootPane,"Erro ao preencher o ArrayList!\nErro:"+ex);
            }
          
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
          Table.setModel(modelo);
          Table.getColumnModel().getColumn(0).setPreferredWidth(190);
          Table.getColumnModel().getColumn(0).setResizable(false);
          Table.getColumnModel().getColumn(1).setPreferredWidth(90);
          Table.getColumnModel().getColumn(1).setResizable(false);  
         // Table.getColumnModel().getColumn(1).setPreferredWidth(200);
          //Table.getColumnModel().getColumn(1).setResizable(false);  
          
          Table.getTableHeader().setReorderingAllowed(false);
          Table.setAutoResizeMode(Table.AUTO_RESIZE_OFF);
          Table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); 
          
          
           
    }
    
    /*
      public void preencherTabelaVendaNomeProdutos(String sql){
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Qt","Mesa","Nome do Produto","Data","Hora"};//
        
         String data = Data.getText();
       String dia, mes, ano; // Variaveis para armazenar data
       
       dia = ""+data.charAt(0)+data.charAt(1)+"/";
       mes = ""+data.charAt(3)+data.charAt(4);
       ano = "/"+data.charAt(6)+data.charAt(7)+data.charAt(8)+data.charAt(9);// mes dia e ano   
      
       
       int anoInt = Integer.parseInt("" + data.charAt(6)+data.charAt(7)+data.charAt(8)+data.charAt(9));// converte o ano para inteiro
       int mesInt = Integer.parseInt(mes);// converte o mes para inteiro
      
        String hora = Hora.getText();// Coloca a hora na tabela
        
        conn.conexao();
        conn.execultasql(sql);                
            try {
                conn.rs.first();
                do {
                  
                  
                  
                    if(mesInt < 10 ){
                    dados.add(new Object[]{j,conn.rs.getString("n_mesa"),conn.rs.getString("nomepd_venda"),dia + "0"+mesInt + "/" + anoInt,hora});
                  //dados.add(new Object[]{j,dia + "0"+mesInt + "/" + anoInt,hora});
                    j++;
                    }else{
                    
                    dados.add(new Object[]{j,conn.rs.getString("n_mesa"),conn.rs.getString("nomepd_venda"),dia + mesInt + "/" + anoInt,hora});
                   
                   //  dados.add(new Object[]{j,dia + mesInt + "/" + anoInt,hora});
                    j++;
                    
                    }
                      
                     
                }while(conn.rs.next());
            } catch (SQLException ex) {
               // JOptionPane.showMessageDialog(rootPane,"Erro ao preencher o ArrayList!\nErro:"+ex);
            }
            
            
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
          jTable1.setModel(modelo);
          jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
          jTable1.getColumnModel().getColumn(0).setResizable(false);
          jTable1.getColumnModel().getColumn(1).setPreferredWidth(70);
          jTable1.getColumnModel().getColumn(1).setResizable(false);  
          jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
          jTable1.getColumnModel().getColumn(2).setResizable(false);  
          jTable1.getColumnModel().getColumn(3).setPreferredWidth(70);
          jTable1.getColumnModel().getColumn(3).setResizable(false);  
          jTable1.getColumnModel().getColumn(4).setPreferredWidth(70);
          jTable1.getColumnModel().getColumn(4).setResizable(false); 
          
          jTable1.getTableHeader().setReorderingAllowed(false);
          jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
          jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                                   
    
          
               
       } */
     
     
     // tabela atualizada com data e hora gravadas no banco
    public void preencherTabelaVendaNomeProdutosContole(String sql){
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Qt","Mesa","Produto","Preço","Data","Hora"};
       
     String hora = Hora.getText();// Coloca a hora na tabela
        
        conn.conexao();
        conn.execultasql(sql);                
            try {
                conn.rs.first();
                do {
                  
                    dados.add(new Object[]{j,conn.rs.getString("n_mesa"),conn.rs.getString("nomepd_venda"),conn.rs.getString("preco_vendac"),conn.rs.getString("data_venda"),conn.rs.getString("hora_venda")});
                    
                    j++;
                   
                   
                }while(conn.rs.next());
            } catch (SQLException ex) {
               // JOptionPane.showMessageDialog(rootPane,"Erro ao preencher o ArrayList!\nErro:"+ex);
            }
       
            
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
          jTable1.setModel(modelo);
          jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
          jTable1.getColumnModel().getColumn(0).setResizable(false);
          jTable1.getColumnModel().getColumn(1).setPreferredWidth(70);
          jTable1.getColumnModel().getColumn(1).setResizable(false);  
          jTable1.getColumnModel().getColumn(2).setPreferredWidth(190);
          jTable1.getColumnModel().getColumn(2).setResizable(false);  
          jTable1.getColumnModel().getColumn(3).setPreferredWidth(60);
          jTable1.getColumnModel().getColumn(3).setResizable(false);  
          jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
          jTable1.getColumnModel().getColumn(4).setResizable(false); 
          jTable1.getColumnModel().getColumn(5).setPreferredWidth(50);
          jTable1.getColumnModel().getColumn(5).setResizable(false); 
          jTable1.getTableHeader().setReorderingAllowed(false);
          jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
          jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                                  
    
       
       }
     
     
     
     
     
       
       // tabela não conectada
       public void preencherTabelaVendaNomeProdutos1(){
        ArrayList dados = new ArrayList();
         
        
        String[] Colunas = new String[]{"Qt","Mesa","Nome do Produto","Data"};//
        
       
        
       
       
       String data = Data.getText();
       String dia, mes, ano; // Variaveis para armazenar data
       
       dia = ""+data.charAt(0)+data.charAt(1)+"/";
       mes = ""+data.charAt(3)+data.charAt(4);
       ano = "/"+data.charAt(6)+data.charAt(7)+data.charAt(8)+data.charAt(9);// mes dia e ano   
      
       
       int anoInt = Integer.parseInt("" + data.charAt(6)+data.charAt(7)+data.charAt(8)+data.charAt(9));// converte o ano para inteiro
       int mesInt = Integer.parseInt(mes);// converte o mes para inteiro
       
       
        Object mesa= jComboBox1.getSelectedItem();// traz a mesa para a tabela
        String produto = ""+Table.getValueAt(Table.getSelectedRow(),0);// nome do produto para a tabela
          
             
             if(mesInt < 10 ){
           
                   dados.add(new Object[]{i,mesa,produto,dia + "0"+mesInt + "/" + anoInt});
                
                 
             }else{
                  
                   dados.add(new Object[]{i,mesa,produto,dia + mesInt + "/" + anoInt});
                  
             }
           
            i++;  
            jProgressBar1.setValue(i);// faz a barra de progresso funcionar
             
           
        /*
        String produto = ""+Table.getValueAt(Table.getSelectedRow(),0);// nome para a tabela
          
                
                   dados.add(new Object[]{i,produto});
                   
                   i++;
                 */
             
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
          jTable1.setModel(modelo);
          jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);//70
          jTable1.getColumnModel().getColumn(0).setResizable(false);
          jTable1.getColumnModel().getColumn(1).setPreferredWidth(90);//190
          jTable1.getColumnModel().getColumn(1).setResizable(false);  
          jTable1.getColumnModel().getColumn(2).setPreferredWidth(190);//200
          jTable1.getColumnModel().getColumn(2).setResizable(false);  
          jTable1.getColumnModel().getColumn(3).setPreferredWidth(200);
          jTable1.getColumnModel().getColumn(3).setResizable(false);  
          
          jTable1.getTableHeader().setReorderingAllowed(false);
          jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
          jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                                   
    
          
    
       
       } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Data;
    private javax.swing.JButton DeletarTabelaControle;
    private javax.swing.JLabel Hora;
    private javax.swing.JButton Somar;
    private javax.swing.JTable Table;
    private javax.swing.JLabel VALOR;
    private javax.swing.JLabel VoltSempre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDinheiro;
    private javax.swing.JLabel jLabelValorTroco;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCodigoVenda;
    private javax.swing.JTextField jTextFieldDinheiro;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldPreco1;
    private javax.swing.JTextField jTextFieldProdConsu;
    private javax.swing.JToggleButton jToggleButtonPesqProd;
    // End of variables declaration//GEN-END:variables
}
